spring:
  profiles:
    include: dict
  datasource:
    hikari:
      username: root
      password: jkxyx205
    url: jdbc:mysql://localhost:3306/project_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.rick.project: trace
    com.rick.db: DEBUG

# mybatis的Mapper位置
mybatis-plus:
#  typeEnumsPackage: com.rick.project.user.dao.enums
  mapper-locations: classpath:mappers/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql