spring:
  datasource:
    hikari:
      username: root
      password: jkxyx205
    url: jdbc:mysql://localhost:3306/project_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  path: /Users/rick/jkxyx205/tmp/iic/log

sharp:
  database:
    type: mysqlRole
